import json
import os

old_file = '/home/sterry/Desktop/GYM_AI/backend/exercises.json'
new_file = '/home/sterry/Desktop/GYM_AI/backend/config/exercises.json'

with open(old_file) as f:
    old_data = json.load(f)

new_data = {"exercises": []}

for key, ex in old_data.items():
    equipment = ex.get('equipment', '')
    if equipment == 'barbell':
        weights_avail = "free_barbell"
    elif equipment == 'dumbbells':
        weights_avail = "free_dumbbell"
    elif equipment == 'bodyweight':
        weights_avail = [0.0]
    else:
        weights_avail = ex.get('custom_increments', [5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0, 45.0, 50.0])

    is_bench = key == 'barbell_bench_press'
    
    # Tier mapping
    # primary: rep_floor: 4, rep_ceiling: 6 (compound barbell/heavy machine movements: bench press, weighted pull-ups, barbell row)
    # heavy: rep_floor: 6, rep_ceiling: 10 (machine compounds: lat pulldown, leg press, leg extension, seated row, incline press, flat dumbbell press)
    # small: rep_floor: 8, rep_ceiling: 15 (isolation: lateral raises, cable flyes, tricep pushdowns, bicep curls, rear delts, frontal raises)
    
    tier = 'small'
    rep_floor = 8
    rep_ceiling = 15
    
    primary_list = ['barbell_bench_press', 'pull_ups', 'machine_closed_row', 'machine_open_row']
    heavy_list = ['lat_pulldowns', 'glute_machine', 'leg_extensions', 'lying_leg_curls', 'hip_abduction_machine', 'flat_dumbbell_bench_press', 'incline_dumbbell_bench_press', 'closed_grip_lat_pulldown']
    
    if key in primary_list:
        tier = 'primary'
        rep_floor = 4
        rep_ceiling = 6
    elif key in heavy_list:
        tier = 'heavy'
        rep_floor = 6
        rep_ceiling = 10
        
    # special for abs
    if 'abs_' in key:
        tier = 'small'
        rep_floor = 10
        rep_ceiling = 20

    new_data["exercises"].append({
        "name": ex["name"],
        "muscle_group": ex["muscle_group"],
        "tier": tier,
        "rep_floor": rep_floor,
        "rep_ceiling": rep_ceiling,
        "weights_available": weights_avail,
        "machine_max": 100.0 if type(weights_avail) == list and len(weights_avail)>1 else None,
        "substitution": None,
        "is_bench_cycle": is_bench,
        "notes": "Autogenerated config."
    })

with open(new_file, 'w') as f:
    json.dump(new_data, f, indent=2)

print(f"Generated {len(new_data['exercises'])} exercises in {new_file}")
